/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x05)
#define ID_BUTTON_0 (GUI_ID_USER + 0x06)
#define ID_BUTTON_1 (GUI_ID_USER + 0x07)
#define ID_BUTTON_2 (GUI_ID_USER + 0x08)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
#define ID_EDIT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char bufferStr[100];
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Keyboard", ID_FRAMEWIN_0, 0, 100, 480, 130, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "ButtonHw", ID_BUTTON_0, 16, 40, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButtonHi", ID_BUTTON_1, 171, 40, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ButtonMcu", ID_BUTTON_2, 354, 40, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hItemButtonHwAction = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
  WM_HWIN hItemButtonHiAction = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
  WM_HWIN hItemButtonMcuAction = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

  char strEdir[100];

  WM_HWIN hItemTestWindowEdit = WM_GetDialogItem(WM_GetDesktopWindowEx(0), ID_EDIT_0);
  WM_HWIN hItemTestWindowText = WM_GetDialogItem(WM_GetDesktopWindowEx(0), ID_TEXT_1);

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Keyboard'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_13_1);
    FRAMEWIN_SetText(hItem, "Framewin Test");
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'ButtonHw'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Hello world");
    //
    // Initialization of 'ButtonHi'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Hi!");
    //
    // Initialization of 'ButtonMcu'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "mcu.by");
    //
    // Initialization of 'ButtonClose'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "Close the window");
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = pMsg->hWin;
    FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'ButtonHw'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        BUTTON_GetText(hItemButtonHwAction, bufferStr, sizeof (bufferStr));

        EDIT_SetText(hItemTestWindowEdit, bufferStr);

        EDIT_GetText(hItemTestWindowEdit, strEdir, sizeof(strEdir));
        TEXT_SetText(hItemTestWindowText, strEdir);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'ButtonHi'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        BUTTON_GetText(hItemButtonHiAction, bufferStr, sizeof (bufferStr));

        EDIT_SetText(hItemTestWindowEdit, bufferStr);

        EDIT_GetText(hItemTestWindowEdit, strEdir, sizeof(strEdir));
        TEXT_SetText(hItemTestWindowText, strEdir);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'ButtonMcu'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        BUTTON_GetText(hItemButtonMcuAction, bufferStr, sizeof (bufferStr));

        EDIT_SetText(hItemTestWindowEdit, bufferStr);

        EDIT_GetText(hItemTestWindowEdit, strEdir, sizeof(strEdir));
        TEXT_SetText(hItemTestWindowText, strEdir);

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateKeyboard
*/
WM_HWIN CreateKeyboard(void);
WM_HWIN CreateKeyboard(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
