/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_SLIDER_0 (GUI_ID_USER + 0x06)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x07)
#define ID_EDIT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
char bufferStr[100] = "Enter text ...";
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "WindowTestButtons", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Click", ID_BUTTON_0, 15, 45, 124, 38, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TextClick", ID_TEXT_0, 15, 5, 116, 31, 0, 0x64, 0 },
  { SLIDER_CreateIndirect, "SliderTest", ID_SLIDER_0, 20, 225, 420, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "ProgbarTest", ID_PROGBAR_0, 20, 185, 420, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "EditTest", ID_EDIT_0, 200, 50, 217, 29, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "TextTest", ID_TEXT_1, 200, 100, 218, 34, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern WM_HWIN CreateKeyboard(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
//  WM_HWIN hItemClickAction = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
  WM_HWIN hItemTextClickAction = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
  WM_HWIN hItemSliderTestAction = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
  WM_HWIN hItemProgbarTestAction = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
//  WM_HWIN hItemEditTestAction = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
//  WM_HWIN hItemTextTestAction = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);

//  char strEdir[100];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Click'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Click");
    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
    //
    // Initialization of 'TextClick'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Click off");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    //
    // Initialization of 'EditTest'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "Enter text ...");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FF8000));
    EDIT_SetFont(hItem, GUI_FONT_32_1);
    //
    // Initialization of 'TextTest'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Enter text ...");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Click'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
         TEXT_SetText(hItemTextClickAction, "Click on");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        TEXT_SetText(hItemTextClickAction, "Click off");
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'SliderTest'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        PROGBAR_SetValue(hItemProgbarTestAction, SLIDER_GetValue(hItemSliderTestAction));
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'EditTest'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        CreateKeyboard();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindowTestButtons
*/
WM_HWIN CreateWindowTestButtons(void);
WM_HWIN CreateWindowTestButtons(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
